export const options = [
  { label: "What's Your DJ Style?", value: 0 },
  { label: 'MC', value: 'MC' },
  { label: 'Tour', value: 'Tour' },
  { label: 'Battle', value: 'Battle' },
  { label: 'Hybrid', value: 'Hybrid' },
  { label: 'Novice', value: 'Novice' },
  { label: 'Digger', value: 'Digger' },
  { label: 'Mobile DJ', value: 'Mobile DJ' },
  { label: 'Live Remix', value: 'Live Remix' },
  { label: 'Producer DJ', value: 'Producer DJ' },
  { label: 'Turntablism', value: 'Turntablism' },
  { label: 'Program Guru', value: 'Program Guru' },
  { label: 'Mad Scientist', value: 'Mad Scientist' },
  { label: 'Radio Mixshow', value: 'Radio Mixshow' },
  { label: 'Night Club Mix', value: 'Night Club Mix' },
  { label: 'Video DJ "VDJ"', value: 'Video DJ "VDJ"' },
  { label: 'Bedroom Bandit', value: 'Bedroom Bandit' },
  { label: 'On air Personality', value: 'On air Personality' },
  { label: 'House & Electronic', value: 'House & Electronic' },
  { label: 'Night Club Scratch', value: 'Night Club Scratch' },
  { label: 'Portable Scratcher', value: 'Portable Scratcher' },
  { label: 'Audio Visual Artist', value: 'Audio Visual Artist' },
  { label: 'I Got My Own Swag Bruh', value: 'I Got My Own Swag Bruh' }
]
